language: node_js
node_js:
  - 6
sudo: required
dist: trusty
install:
  - bundle install
  - npm install -g grunt-cli
  - npm install -g bigcommerce/stencil-cli
  - npm install
script:
  - grunt check
  - stencil bundle
