language: node_js
node_js:
- 4
sudo: required
dist: trusty
group: deprecated-2017Q4
install:
- bundle install
- npm install -g grunt-cli
- npm install -g bigcommerce/stencil-cli
- npm install
script:
- grunt check
- stencil bundle
